/** @type {import('tailwindcss').Config} */
export default {
  content: ['./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}'],
  theme: {
    extend: {
      colors: {
        'primary': '#022448',
        'secondary': '#006a60',
        'primary-container': '#1e3a5f',
        'secondary-container': '#8cf5e4',
        'on-primary': '#ffffff',
        'on-secondary': '#ffffff',
        'on-surface': '#191c1d',
        'on-surface-variant': '#43474e',
        'on-background': '#191c1d',
        'on-primary-container': '#8aa4cf',
        'on-secondary-container': '#007166',
        'on-error': '#ffffff',
        'on-error-container': '#93000a',
        'on-tertiary': '#ffffff',
        'on-tertiary-container': '#c69b5f',
        'on-primary-fixed': '#001c3b',
        'on-primary-fixed-variant': '#2d486d',
        'on-secondary-fixed': '#00201c',
        'on-secondary-fixed-variant': '#005048',
        'on-tertiary-fixed': '#291800',
        'on-tertiary-fixed-variant': '#60410c',
        'surface': '#f8f9fa',
        'surface-bright': '#f8f9fa',
        'surface-dim': '#d9dadb',
        'surface-container': '#edeeef',
        'surface-container-low': '#f3f4f5',
        'surface-container-lowest': '#ffffff',
        'surface-container-high': '#e7e8e9',
        'surface-container-highest': '#e1e3e4',
        'surface-variant': '#e1e3e4',
        'surface-tint': '#455f87',
        'background': '#f8f9fa',
        'outline': '#74777f',
        'outline-variant': '#c4c6cf',
        'inverse-surface': '#2e3132',
        'inverse-on-surface': '#f0f1f2',
        'inverse-primary': '#adc8f5',
        'error': '#ba1a1a',
        'error-container': '#ffdad6',
        'tertiary': '#341f00',
        'tertiary-container': '#503300',
        'tertiary-fixed': '#ffddb2',
        'tertiary-fixed-dim': '#edbf7f',
        'primary-fixed': '#d5e3ff',
        'primary-fixed-dim': '#adc8f5',
        'secondary-fixed': '#8cf5e4',
        'secondary-fixed-dim': '#6fd8c8',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        '3xl': '1.5rem',
        full: '9999px',
      },
      fontFamily: {
        headline: ['Manrope', 'sans-serif'],
        body: ['Public Sans', 'Noto Sans TC', 'sans-serif'],
        label: ['Public Sans', 'sans-serif'],
      },
    },
  },
  plugins: [],
};
